-- DentalPhotoOrganizer Phase 2-C
-- Development seed data for Dashboard statistics.
-- Run this after supabase/schema.sql in the Supabase SQL Editor.

insert into public.photos (
  original_filename,
  original_path,
  file_hash,
  file_size,
  mime_type,
  captured_at,
  imported_at,
  provisional_patient_id,
  doctor_name,
  photographer_name,
  review_status,
  export_status,
  reviewer_id,
  reviewed_at,
  approved_at,
  notes
) values
  (
    'IMG_0001.JPG',
    'E:/DCIM/100DENTAL/IMG_0001.JPG',
    'dev-hash-0001',
    2481120,
    'image/jpeg',
    current_date + time '09:10',
    now() - interval '2 hours',
    'P-DEV-001',
    'Dr. Nakamura',
    'M. Tanaka',
    'pending',
    'not_exported',
    null,
    null,
    null,
    '今日取り込み、レビュー待ち'
  ),
  (
    'IMG_0002.JPG',
    'E:/DCIM/100DENTAL/IMG_0002.JPG',
    'dev-hash-0002',
    2519040,
    'image/jpeg',
    current_date + time '09:12',
    now() - interval '90 minutes',
    'P-DEV-001',
    'Dr. Nakamura',
    'M. Tanaka',
    'approved',
    'ready_for_export',
    'reviewer-dev',
    now() - interval '30 minutes',
    now() - interval '20 minutes',
    '今日取り込み、承認済み'
  ),
  (
    'IMG_0003.JPG',
    'E:/DCIM/100DENTAL/IMG_0003.JPG',
    'dev-hash-0003',
    2448768,
    'image/jpeg',
    current_date + time '10:05',
    now() - interval '45 minutes',
    'P-DEV-002',
    'Dr. Sato',
    'A. Suzuki',
    'pending',
    'not_exported',
    null,
    null,
    null,
    '今日取り込み、レビュー待ち'
  ),
  (
    'IMG_OLD_0001.JPG',
    'E:/DCIM/100DENTAL/IMG_OLD_0001.JPG',
    'dev-hash-old-0001',
    2390016,
    'image/jpeg',
    (current_date - interval '3 days') + time '15:20',
    now() - interval '3 days',
    'P-DEV-003',
    'Dr. Nakamura',
    'M. Tanaka',
    'approved',
    'exported',
    'reviewer-dev',
    now() - interval '2 days',
    now() - interval '2 days',
    '過去取り込み、承認済み'
  ),
  (
    'IMG_OLD_0002.JPG',
    'E:/DCIM/100DENTAL/IMG_OLD_0002.JPG',
    'dev-hash-old-0002',
    2463200,
    'image/jpeg',
    (current_date - interval '1 day') + time '11:30',
    now() - interval '1 day',
    'P-DEV-004',
    'Dr. Ito',
    'A. Suzuki',
    'reviewing',
    'not_exported',
    'reviewer-dev',
    now() - interval '12 hours',
    null,
    '過去取り込み、確認中'
  );
